name: Run Unit & E2E (Playwright) Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install app dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:no-watch

      - name: Install Playwrite Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e
